### ISSUE TITLE
Link gun primary and secondary stats are backwards. Primary is showing secondary and secondary is showing primary.

### ISSUE THREAD

**Issue by v-k-g** [mich-devs/3SPNRU#10]
![image](https://user-images.githubusercontent.com/73268658/97757124-1dc38180-1aca-11eb-9613-862bb1d43fc1.png)

**Comment by v-k-g** [comment]
Fun fact: This goes back to the development of NewNet and exists in every version of tam using NewNet. In code below, notice that LinkFire references a LinkedVehicle, which refers to the alt fire. Code in this file is consistent with the alt fire even though it's labeled LinkFire. Similarly, LinkAltFire references projectiles and is setup to handle those.

![image](https://user-images.githubusercontent.com/73268658/97757885-b73f6300-1acb-11eb-8cc9-1040a8f425a2.png)

**Comment by v-k-g** [comment]
A few options here:
A) Swap functionality at the base level in NewNet, probably the most work
B) Swap display of primary/secondary fire, probably the least work but does not fix the underlying problem
C) Fix somewhere inbetween NewNet and display. I'm a hard no on this option but it's certainly possible.

**Comment by hvownij** [comment]
Issue with  latest commits = squashed.

Acc %'s also fixed.  

Resolving issue!


Thanks for your work Viking!
