### ISSUE TITLE
Beta-1 Camper warning

### ISSUE THREAD

**Issue by hvownij** [mich-devs/3SPNRU#2]
YouAreCampingFirst="FIRST OFFENSE!"

This is the only message that is showing up when you get multiple camper warnings.

We need to tweak this?  Should it just change to a generic message?  Do we want it to kill the player after x amount of times?

**Comment by mGm-Lizard** [comment]
Kill the player after 2 consecutive offences.

**Comment by grahamslam** [comment]
The GetString Function in the Camper_Message class has some illogical logic

**Comment by hvownij** [comment]
So after further investigation, this issue persists across all 3spn versions.  It goes camper warning -> first offense and keeps repeating it.

Its a non issue.

Renaming " first offense " to something else.  Problem solved.
