### ISSUE TITLE
Menu_DamageTab.uc & Menu_Menu3SPN.uc

### ISSUE THREAD

**Issue by hvownij** [mich-devs/3SPNRU#3]
Everything was added in to mirror 3SPN AT Damage indicators.  It compiles.  We do not have the ability to open the Damage Visuals menu in the 3SPN menu.  We also do not know if even when we can do this, if the damage indicators are functional.  The serverside option is a checkbox when you are in webadmin / launching a server.

This is the only problem child we have at the moment.

Error: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:003A) Accessed array 'Controls' out of bounds (23/1)
Warning: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:003A) Accessed None 'Controls'
Warning: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:0042) Attempt to assign variable through None
Error: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:0054) Accessed array 'Controls' out of bounds (1/1)
Warning: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:0054) Accessed None 'Controls'
Error: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:006C) Accessed array 'Controls' out of bounds (24/1)
Warning: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:006C) Accessed None 'Controls'
Warning: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:0074) Attempt to assign variable through None
Error: Menu_TabDamage Package.Menu_TabDamage (Function 3SPNRU-B1.Menu_TabDamage.InitComponent:0087) Accessed array 'Controls' out of bounds (2/1)

This is what shows up in the log for UT2004.exe when clicking on the menu tab.

Here is the file-> https://github.com/mich-devs/3SPNRU/blob/Beta-1/Classes/Menu_TabDamage.uc

Here is what we have to reference -> https://github.com/mich-devs/3SPNRU/blob/3SPNv3177AT/Classes/Menu_TabMisc.uc]

Look for the lines that have DamageIndicator or DamageCheck or DamageCheck2.

I have tried multiple ideas.

here is what I get when trying to compile with what we have.

Unknown property in defaults: Controls(26)=GUILabel'3SPNRU-B1.Menu_TabDamage.DamageLabel.

it works for
Controls(23)=moCheckBox'3SPNRU-B1.Menu_TabDamage.DamageCheck'

does not work for

//    Controls(24)=moCheckBox'3SPNRU-B1.Menu_TabDamage.DamageCheck2'

Hopefully we can work together and squash this bug!  Then we can find out if the indicators even are working.

Thanks
Hv

**Comment by hvownij** [comment]
Progress has been made!

The menu works, both options show up under the correct checkbox.

However, when you click the checkbox it does not produce a check.  you close the menu and reopen it, there is a check in the box.

you can disable and enable the features without issue beyond this.

Needs more polish!

Thanks to f00l for figuring this out!

**Comment by mGm-Lizard** [comment]
is this even an issue anymore?

**Comment by hvownij** [comment]
No longer a major issue.

We would eventually like when you check one option you cannot check the other OR it removes the check from the box when you selected a different one.

If you choose both it will only enable the last one selected but both can get filled with a [x].

**Comment by hvownij** [comment]
100% fixed.  Maybe a change in future to a dropdown instead but closing issue as it is resolved for current implementation

**Comment by v-k-g** [comment]
PR #20 fixes this tab. Can close this issue once merged.
