### ISSUE TITLE
Add Hit column

### ISSUE THREAD

**Issue by v-k-g** [mich-devs/3SPNRU#9]
1. Hit column should appear between Fired and Acc columns
2. Hit column should display the the number of shots hit for the given weapon
3. Hit / Fired should always = Acc

**Comment by hvownij** [comment]
This is definitely something we need!  going to assign this to you if you do not mind

**Comment by v-k-g** [comment]
Can be closed after merging this PR: https://github.com/mich-devs/3SPNRU/pull/23
